name       : x11vnc
version    : 0.9.15
release    : 2
source     :
    - https://github.com/LibVNC/x11vnc/archive/0.9.15.tar.gz : 3e43bd875edc3c7f52a0d3676c4ec7de910fcd210240ee20b4522deb2bf84cff
license    : GPL-2.0-or-later
component  : network.util
summary    : a VNC server for real X displays
description: |
    a VNC server for real X displays
builddeps  :
    - pkgconfig(libvncserver)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
