name       : x11vnc
version    : 0.9.16
release    : 5
source     :
    - https://github.com/LibVNC/x11vnc/archive/0.9.16.tar.gz : 885e5b5f5f25eec6f9e4a1e8be3d0ac71a686331ee1cfb442dba391111bd32bd
license    : GPL-2.0-or-later
component  : network.util
summary    : a VNC server for real X displays
description: |
    a VNC server for real X displays
builddeps  :
    - pkgconfig(libvncserver)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
